name: CI

on: [push, pull_request]

env:
  HOMEBREW_NO_ANALYTICS: "ON" # Make Homebrew installation a little quicker
  HOMEBREW_NO_AUTO_UPDATE: "ON"
  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
  HOMEBREW_NO_GITHUB_API: "ON"
  HOMEBREW_NO_INSTALL_CLEANUP: "ON"

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Build and test (Windows)
      if: contains(matrix.os, 'windows')
      run: |
          ci\compile_test.bat
          examples\Release\colors.exe

    - name: Build and test (Linux / macOS)
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
      run: |
          bash ci/compile_test.sh
          bash ci/tests.sh
