name: cpp-linter

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/cpp-linter.yml'
  pull_request:
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/cpp-linter.yml'
  workflow_dispatch:

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 📂 Load .env file
        if: hashFiles('.github/workflows/.env') != ''
        uses: xom9ikk/dotenv@v2
        with:
          path: .github/workflows

      - name: ⬇️ Setup CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ^3
          ninjaVersion: ^1.11.1

      - name: 🔧 Configure
        run: cmake -S ${{ env.CMAKE_SOURCE_PREFIX }} -B ${{ env.CMAKE_BINARY_PREFIX }} -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} -DCMAKE_PREFIX_PATH="~/micromamba" -DCMAKE_INSTALL_PREFIX=${{ env.CMAKE_INSTALL_PREFIX }}  -D CPPTERMINAL_ENABLE_DOCS=OFF

      - name: ☑️ cpp-linter
        uses: cpp-linter/cpp-linter-action@v3
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'
          database: ${{ env.CMAKE_BINARY_PREFIX }}
          step-summary: true
          thread-comments: true
          files-changed-only: true
          lines-changed-only: false
          version: '17'
          tidy-checks: ''
          ignore: '.github|${{ env.CMAKE_BINARY_PREFIX }}/_deps'
