name: MacOS CI

on: [push, pull_request]

env:
  HOMEBREW_NO_ANALYTICS: "ON" # Make Homebrew installation a little quicker
  HOMEBREW_NO_AUTO_UPDATE: "ON"
  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
  HOMEBREW_NO_GITHUB_API: "ON"
  HOMEBREW_NO_INSTALL_CLEANUP: "ON"

jobs:
  Build:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: bash ci/compile_test.sh
    
    - name: Test
      run: bash ci/tests.sh

    - name: Standalone
      run: cmake -DCMAKE_INSTALL_PREFIX=./standalone-install -DCMAKE_PREFIX_PATH=${{ github.workspace }}/install/ -S ./tests/test-standalone -B ./standalone-build; cmake --build ./standalone-build ; cmake --install ./standalone-build
